<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TXCHD-LAP-360" failures="1" tests="1" name="Cucumeber Test" time="13.407" errors="0" timestamp="2023-08-28T17:34:00 IST">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="11.523">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [true] but found [false]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at stepDefinitions.SignUp.SignUp.validateErrorMessageAssociatedToFieldFor(SignUp.java:29)
at âœ½.And validate error message associated to "Name" field for "RR001"(SignUp.feature:10)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Cucumeber Test -->
